server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SkincareBooking
    username: root
    password: root
  #  url: jdbc:mysql://5vpsce.stackhero-network.com:7666/dd62um1g91bup1w
  #  username: root
  #  password: jAEH7iIUpNvI7QBi8i4fIajFfymlBATk
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  signerKey: "WpNCZp8lxQ3kmkhy66PYLlrZXjPWUNWkkL1kNUktafsDr53o2dmGb4wB1AX6Tz2S"
