name: Deploy to Heroku

on:
  push:
    branches:
      - main # Thay 'main' bằng nhánh chính của bạn nếu khác

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Thay bằng phiên bản Java của bạn
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests # Bỏ qua test nếu không cần

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
